# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantallaRegistroPresion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Presion(object):
    def setupUi(self, Presion):
        Presion.setObjectName("Presion")
        Presion.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Presion)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pB_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.pB_iniciar.setObjectName("pB_iniciar")
        self.verticalLayout.addWidget(self.pB_iniciar)
        self.pB_finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.pB_finalizar.setObjectName("pB_finalizar")
        self.verticalLayout.addWidget(self.pB_finalizar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pB_grabar = QtWidgets.QPushButton(self.centralwidget)
        self.pB_grabar.setObjectName("pB_grabar")
        self.horizontalLayout_2.addWidget(self.pB_grabar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lbl_Tiempo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Tiempo.setObjectName("lbl_Tiempo")
        self.horizontalLayout_2.addWidget(self.lbl_Tiempo)
        self.sB_Tiempo = QtWidgets.QSpinBox(self.centralwidget)
        self.sB_Tiempo.setMaximum(1000000)
        self.sB_Tiempo.setProperty("value", 100)
        self.sB_Tiempo.setObjectName("sB_Tiempo")
        self.horizontalLayout_2.addWidget(self.sB_Tiempo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.ventanaPlot = PlotWidget(self.centralwidget)
        self.ventanaPlot.setObjectName("ventanaPlot")
        self.verticalLayout_2.addWidget(self.ventanaPlot)
        Presion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Presion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        Presion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Presion)
        self.statusbar.setObjectName("statusbar")
        Presion.setStatusBar(self.statusbar)
        self.accionSalir = QtWidgets.QAction(Presion)
        self.accionSalir.setObjectName("accionSalir")
        self.actionAyuda = QtWidgets.QAction(Presion)
        self.actionAyuda.setObjectName("actionAyuda")
        self.menuArchivo.addAction(self.accionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(Presion)
        QtCore.QMetaObject.connectSlotsByName(Presion)

    def retranslateUi(self, Presion):
        _translate = QtCore.QCoreApplication.translate
        Presion.setWindowTitle(_translate("Presion", "Registro de Presión"))
        self.pB_iniciar.setText(_translate("Presion", "Iniciar"))
        self.pB_finalizar.setText(_translate("Presion", "Finalizar"))
        self.pB_grabar.setText(_translate("Presion", "Grabar"))
        self.lbl_Tiempo.setText(_translate("Presion", "Tiempo [s]"))
        self.menuArchivo.setTitle(_translate("Presion", "Archivo"))
        self.accionSalir.setText(_translate("Presion", "Salir"))
        self.actionAyuda.setText(_translate("Presion", "Ayuda"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Presion = QtWidgets.QMainWindow()
    ui = Ui_Presion()
    ui.setupUi(Presion)
    Presion.show()
    sys.exit(app.exec_())
